#!/usr/bin/env bash

# Install zimfw zsh framework and plugin manager
sudo curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

# Install chezmoi and apply dotfiles
sudo sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply khanhgee

if [[ $HOSTNAME = *.github.net || -n $CODESPACES ]]; then
  if [[ -n $BASH && $- == *i* ]] && command -v zsh >/dev/null; then
    exec zsh -l
  fi

  # export EMAIL=khanhgee@github.com
fi
