#! /bin/bash

DIR="$(cd "$(dirname "$0")" && pwd)"

# Install zsh before all else
sudo apt install zsh -y

# Install zimfw zsh framework and plugin manager
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh

# Install chezmoi and apply dotfiles
sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply khanhgee

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1

if [ $MACOS ]; then
  VSCODE="$HOME/Library/Application Support/Code/User"
elif [ $LINUX ]; then
  VSCODE="$HOME/.config/Code/User"
fi

cp ../vscode-settings.json "$VSCODE/settings.json"

USER=${USER:-$(id -un)}

if [[ $HOSTNAME = *.github.net || -n $CODESPACES ]]; then
  rm -vf .bash* .profile
fi

chsh_zsh() {
  if [[ $(getent passwd "$USER") != */zsh ]]; then
    sudo -n chsh -s /bin/zsh $USER
  fi
}

if [[ -n $CODESPACES ]]; then
  mv .zshrc .zshrc-codespaces
  ln -nsfv /workspaces/.codespaces/.persistedshare/dotfiles .dotfiles
  [[ -f .gitconfig ]] && mv -v .gitconfig .config/git/local
  chsh_zsh
fi

# GHES
if [[ $USER = build && $HOME = /workspace ]]; then
  chsh_zsh

  # rm -f ~/.gitconfig

  # (cd ~/enterprise2)
fi

"$DIR/install-vscode-extensions"
